### ISSUE TITLE
How can I clear the screen with C-l

### ISSUE THREAD

**Issue by lnc3l0t** [aserowy/tmux.nvim#102]
This may be a stupid question, but aside from remapping the navigation to use ALT+key instead of CTRL+key how can I keep the bash behaviour of `CTRL-l` to clear the screen.

I use ALT+{h,l} to cycle bufferline, and I would like to keep it

**Comment by aserowy** [comment]
I guess, there is no way besides remapping.

https://github.com/aserowy/tmux.nvim/blob/03e28fdaa2ef54b975ba1930f1e69b5e231dedc9/lua/tmux/navigation/init.lua#L7

Disable this option and customize your remapping. Important: Do not forget to customize the tmux side as well.

Kind regards
Alexander
