### ISSUE TITLE
Searching for neovim process on Nix

### ISSUE THREAD

**Issue by carschandler** [aserowy/tmux.nvim#103]
If you have installed neovim via Nix, the recommended grep expression won't match the process name that `ps` returns. In most cases, nix users are installing a wrapped version of neovim that shows up as `.nvim-wrapped`. This line is working for me as of now in my `tmux.conf`:

`is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.nvim-wrapped$'"`

The wrapped version runs under this process name for diff mode as well, so no need to worry about the name changing for other modes (in my case, at least)

May want to add this to the README :)

**Comment by aserowy** [comment]
Heho,

ty for the reply. I extended the existing regexes to enable .nvim-wrapped out of the box.

Kind regards
Alexander
