### ISSUE TITLE
statusline disappear when cmdheight=0

### ISSUE THREAD

**Issue by aca** [aserowy/tmux.nvim#105]
Hi,
I'm not sure what is going on. But when I go to other tmux pane inside vim.
vim's statusline disappear (or just a message).
When I just move pane with tmux command it remains.

https://asciinema.org/a/IdmJ2Ko2hwFYLQlDnUNsmftF8

**Comment by aserowy** [comment]
Heho,

this is weird. And this behavior only happens with the plugin active?

Kind regards
Alexander

**Comment by aca** [comment]
yap, it seems like cmdline remains. any clue to fix this?

**Comment by aserowy** [comment]
sorry, not really. Since im not using tmux anymore my motivation is... :D If youll find it, i would love to see a pr.

Kind regards
Alexander

**Comment by net** [comment]
@aca did you find a fix for this?

**Comment by aca** [comment]
https://github.com/aca/tmux.nvim/commit/ab74aa502c505cf04440cfea211bb96930d082a4
Here's a fix. I just forked...

**Comment by net** [comment]
@aca amazing, that worked!

Do you think you open a PR? If not, I can.

**Comment by aca** [comment]
Was not sure if is also problem for others. I'll create pr.

**Comment by aserowy** [comment]
tyvm
