### ISSUE TITLE
Navigating out of lazy.nvim window results in Error: WinLeave Autocommands ...

### ISSUE THREAD

**Issue by oschrenk** [aserowy/tmux.nvim#107]
I am using https://github.com/folke/lazy.nvim as my package manager and when I open it via `:Lazy` it opens a floating window in nvim.

Trying to then navigate using tmux.nvim results in:

```
E5108: Error executing lua ...are/nvim/lazy/tmux.nvim/lua/tmux/navigation/
navigate.lua:37: WinLeave Autocommands for "*": Vim(substitute):E21: Cannot make changes, 'modifiable' is off
stack traceback:
        [C]: in function 'wincmd'
        ...are/nvim/lazy/tmux.nvim/lua/tmux/navigation/navigate.lua:37: in
 function 'to'
        ...l/share/nvim/lazy/tmux.nvim/lua/tmux/navigation/init.lua:30: in
 function 'move_right'
        [string ":lua"]:1: in main chunk
```

My config

```
return {
  "aserowy/tmux.nvim",
  keys = { "<C-h>", "<C-j>", "<C-k>", "<C-l>" },
  config = function()
    require("tmux").setup({
      copy_sync = { enable = false },
      navigation = { cycle_navigation = true, enable_default_keybindings = true },
      resize = { enable_default_keybindings = true, resize_step_x = 1, resize_step_y = 1 },
    })
  end,
}
```

My best guess is that I am missing some config flag for floating windows, but I also feel that it was happening only since my upgrade from nvim 0.9.2 to 0.9.4. I'm suspecting that maybe https://github.com/neovim/neovim/pull/25523 introduced an issue (it did for other plugins using auto_cmd

**Comment by aserowy** [comment]
Heho,

is this still relevant? The only auto cmds in tmux nvim are separated. Those should not lead to an error.

Kind regards
Alexander

**Comment by oschrenk** [comment]
Let's close it. It's still occurring but I'm having a hard time finding the source of the error. It expresses itself mostly when using tmux.nvim but I guess it's not the source of the error.

**Comment by oschrenk** [comment]
Still investigating. I reverted to https://github.com/christoomey/vim-tmux-navigator to see if it changes things. I still get an error but the error is now maybe more clear )well at least different):

I get

```
E11: Invalid in command-line window; <CR> executes, CTRL-C quits: wincm
d k
```

It still works but it still shows an error.

It comes from here:

```
function! s:VimNavigate(direction)
  try
    execute 'wincmd ' . a:direction
  catch
    echohl ErrorMsg | echo 'E11: Invalid in command-line window; <CR> executes, CTRL-C quits: wincmd k' | echohl None
  endtry
endfunction
```

I would think that there is something special about the :Lazy window. I also assume that your plugin also relies on `wincmd` and it perhaps fails the same way .

It seems it's maybe not about Winleave autocmd but just about applying `wincmd` on a special window. 

I also opened a discussion over at https://github.com/folke/lazy.nvim/discussions/1156

**Comment by aserowy** [comment]
ill follow it. lets see what we get.

**Comment by oschrenk** [comment]
I also found  an issue from 2015

https://github.com/christoomey/vim-tmux-navigator/issues/67

and actually removing/commenting out the `echohl` line

```
function! s:VimNavigate(direction)
  try
    execute 'wincmd ' . a:direction
  catch
    " echohl ErrorMsg | echo 'E11: Invalid in command-line window; <CR> executes, CTRL-C quits: wincmd k' | echohl None
  endtry
endfunction
```

in the "original" christoomey/vim-tmux-navigator code actually still works. It's jumping to the pane.

It seems that there is some issue with vim vs nvim and commandline windows.

**Comment by oschrenk** [comment]
It was my own configuration 🤦

```
local my_actions = augroup("MyActions", { clear = true })

-- Autosave on focus lost or when exiting the buffer
autocmd({ "FocusLost", "WinLeave" }, {
  pattern = "*",
  command = ":...",
  group = my_actions,
})
```

The autocmd fired on `lazy ` window and created issues with non modifiable windows. Nothing to do with tmux.
