### ISSUE TITLE
Enhancement: Not jump to other tmux pane if current pane is in fullscreen

### ISSUE THREAD

**Issue by imroc** [aserowy/tmux.nvim#108]
When there are a few windows in neovim, and also a few pane in tmux window, and current pane is in fullscreen, I use `C-hjkl` to jump to other window in neovim, but it jumped to other tmux pane, which is not what I wanted, If we can disable jump tmux panes in fullscreen, it would be useful.

**Comment by aserowy** [comment]
Heho,

i guess you are looking for the following config entry. Let me know, if this is what you meant.

```
navigation = {
        -- prevents unzoom tmux when navigating beyond vim border
        persist_zoom = true,
...
```

**Comment by imroc** [comment]
@aserowy Cool, thanks, that's just what I wanted
