### ISSUE TITLE
Add wezterm support as a new backend beside tmux

### ISSUE THREAD

**Issue by illia-danko** [aserowy/tmux.nvim#109]
Hey there. I had been a long neovim + tmux Ctrl[j,jk,h,l] user for long time. And recently found another alternative setup which satisfies all my needs. It's [wezterm](https://github.com/wez/wezterm) + its built-in multiplexer, which gives me:
- a multiplexer ability to split panes and create a new tab instance
- use copy mode with vim like keybinding
- built-in ssh support
- and finally, as a bonus, to preview images and having terminal multiplexing at the same time! Which is awesome!

The only missing part is make it works with the Ctrl[j,jk,h,l] nav workflow: to switch back and forth between panes and neovim windows seamlessly (resize panes as well, which I do not use). The solution for [emacs + evil (vim binds)](https://codeberg.org/eli87/evil-wezterm-navigator)  is already implemented. And perhaps, it is time to make it work for neovim as well.
The trick is to ask wezterm about the available panes at the interested side and use these ids to direct navigation like:
```sh
wezterm cli get-pane-direction right # capture id number as stdout output
wezterm cli activate-pane --pane-id 46 # use the id
``` 
What about to create a new backend (lets say `wezterm`) and make the plugin work for wezterm also? Thank you for any input.

**Comment by aserowy** [comment]
Heho,

nice you discovered wezterm! Awesome terminal! I guess it would be worth another plugin to not drive more complexity into this one. The current implementation would deviate quite a bit.

Maybe willothys plugin already fits your needs.

A good starting point would be:

- https://github.com/wez/wezterm/discussions/995
- https://github.com/willothy/wezterm.nvim/
