### ISSUE TITLE
tmux.nvim copy_sync related crash

### ISSUE THREAD

**Issue by arminveres** [aserowy/tmux.nvim#111]
Hi there,
I am using the newest version of this plugin, with Neovim on nightly, and for the past few weeks, I have been experiencing a crash of this plugin while inside Neovim. It manifests after around 10-15 minutes of being open.

```
     4 stack traceback:
     5 >       [C]: in function 'assert'
     6 >       ...ocal/share/nvim/lazy/tmux.nvim/lua/tmux/wrapper/tmux.lua:27: in function 'execute'
     7 >       ...ocal/share/nvim/lazy/tmux.nvim/lua/tmux/wrapper/tmux.lua:70: in function 'get_buffer_names'
     8 >       ...veres/.local/share/nvim/lazy/tmux.nvim/lua/tmux/copy.lua:29: in function <...veres/.local/share/nvim/lazy/tmux.nvim/lua/tmux/copy.lua:20>
     9 07:36:18 PM msg_show ...ocal/share/nvim/lazy/tmux.nvim/lua/tmux/wrapper/tmux.lua:27: unable to execute: [ tmux -S /tmp/tmux-1000/default  list-buffers -F "#{buffer_name}" ]
```

#### UPDATE:
Tmux version: `3.3a-7.20230918gitb202a2f.fc39`
Evidently, I am using Fedora Workstation 39.

Additionally, I am getting an error: `Failed to start process: Too many open files` for xclip or for e.g., zsh when wanting to open a terminal.

**Comment by aserowy** [comment]
Was there a tmux update as well?

Can you please try to execute the listed call after the plugin crashed? I suspect, this behavior is caused by tmux because the assert checks if the call succeded.

**Comment by aserowy** [comment]
Heho,

sry for the late response. It seems the call against tmux fails/times out. Because the error occurs in the assert. The plugin itself is not crashing/bugging out.

Since im not actively dev the plugin anymore im still maintaining it. I would be glad if you can debug and pr a fix.

Kind regards
Alexander

**Comment by arminveres** [comment]
Hi @aserowy, no worries, in the meantime I found out, that some change in Fedora 39 probably reduced the user limit of open files, so the crash has nothing to do with your plugin! Sorry for the confusion and thanks for the plugin

SOLUTION:
Globally update the limit of open files in `sudoedit /etc/security/limits.conf` by appending this line:
```
* soft nofile 8192
```
Which was originally 1024.

**Comment by aserowy** [comment]
Nice that you found a solution! It was a nice experience to write even if im not using it anymore. Neovim is <3 :D
