### ISSUE TITLE
Add option to overwrite the is_vim command.

### ISSUE THREAD

**Issue by Feferoni** [aserowy/tmux.nvim#114]
Would be great if you could add the option to be able to overwrite the is_vim command so that other programs than vim/nvim could be included. 

Because when I use fzf for different things in the terminal, I want to be able to navigate up/down with the ctrl + k / j. 

Solved it with:
`
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?(g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$|fzf)$'"
`

But would be great to be able to set this from the .tmux.conf.

**Comment by aserowy** [comment]
Heho,

like i wrote in the readme, i am no longer actively developing but maintaining the plugin. Feel free to pr the funcionallity.

Tyvm and kind regards
Alexander
