### ISSUE TITLE
Support specifying resize step in `resize_*` methods

### ISSUE THREAD

**Issue by rudenkornk** [aserowy/tmux.nvim#125]
Currently, `require("tmux").resize_left()` and similar methods do not allow to specify resize step. They only inherit it from the global configuration.

In case one needs to specify different keys for different resize precision, this becomes inconvenient. 
For example, I would like to  set smth like `<A-h>` for coarse resizing and `<A-H>` for more presize one.

**Comment by aserowy** [comment]
nice idea, you can pr anytime (if you like of course).

kind regards
Alexander
