### ISSUE TITLE
Clipboard selection

### ISSUE THREAD

**Issue by Shourai** [aserowy/tmux.nvim#16]
Hey @aserowy,

I am using this plugin as alternative to https://github.com/christoomey/vim-tmux-navigator.
Moving around and reszing works.
Although I needed to `PackerCompile` everything first, this wasn't necessary for other plugins so I was confused at first why it wasn't working.

A different issue that I stumbled on is that yanking from nvim it seems that the selection is yanked into `PRIMARY`.
I can paste this selection into a different tmux window with `middle mouse click` just fine and also paasting between nvim sessions works.

However would it be possible that the yanked text to be synced to `CLIPBOARD` instead?
For multiple use-cases:

1. Yank something from nvim and paste it somewhere else that isn't tmux e.g. browser
2. Yank text from a remote nvim/tmux session and have it synced to local clipboard using X11 forwarding.

**Comment by aserowy** [comment]
Hi, 

sry for the late response. rl, work.. :D and thanks using this plugin 👍 
PackerCompile is needed, if you setup the settings directly in the config function, because (in my understanding) the setup object will get compiled as well. Thus, you can refactor the setup in a custom object. That way only the require("blub") gets compiled.

To your request: If you are running tmux >= 3.2 you can enable redirect_to_clipboard. This way, tmux will take care to add the yank to your clipboard. For <3.2 im not sure how to handle it. Would it help to be able to configure if vim.g.clipboard will get set?
Currently it will get set automatically here: https://github.com/aserowy/tmux.nvim/blob/88face36091992eeb8da2891e5c874b8a9831210/lua/tmux/copy.lua#L108

Kind regards
Alexander

**Comment by Shourai** [comment]
Hey @aserowy,

thanks for your reply.
I do have `redirect_to_clipboard` enabled and running tmux 3.2a.

```lua
  use {
    "aserowy/tmux.nvim",
    config = function()
      require("tmux").setup({
        copy_sync = { enable = true,
        redirect_to_clipboard = true },
        navigation = { enable_default_keybindings = true },
        resize = { enable_default_keybindings = true } })
      end
    }
```
What I noticed is that when I don't use tmux, I do yank everything to clipboard.
But that I probably due to `unnamedplus` setting.

**Comment by aserowy** [comment]
(sry for the long absence, holyday :D)

Hmm this is strange. On my end it works exactly like that. I guess you are configuring the vim.o.clipboard after you load the plugin? Thus, you would overwrite the functionality.
It bugs me :D Do you get the history in your tmux buffer as well and copying in tmux lets you paste from registers?

Kind regards
Alexander

**Comment by Shourai** [comment]
Hey @aserowy,

hope you had a nice holiday!

You are correct that the plugins get loaded after the `vim.o.` settings.
I switched around https://github.com/Shourai/dotfiles/blob/89dd56691ccfd0fc8a8df8bb691ee6f900bf2d16/nvim/init.lua#L4 with line 5.
Next I tried commenting out https://github.com/Shourai/dotfiles/blob/89dd56691ccfd0fc8a8df8bb691ee6f900bf2d16/nvim/lua/settings.lua#L9 but to no avail.

With `vim.o.clipboard` commented out I get the following:
When I copy something from tmux the registers `", 0, *, +` are populated by what I copied.
When I yank something from vim, the same registers are populated.

But when I paste something I yanked from vim into my terminal I don't get what I yanked.

**Comment by aserowy** [comment]
Can you plz post :reg and tmux list-buffers after yanking in tmux and after yanking in nvim? Maybe the sync is not working.
You can set the debug level in your configuration with { logging = { file = "debug" }, options = ... }.
Plz post the logs written under vim.fn.stdpath("cache") .. "/" as well.

Btw. thx for your help and interest! 👍 

Kind regards

**Comment by pedro757** [comment]
I found that when i try to copy, delete, ct with the copy feature of this plugin enabled, it actually **crashes** my neovim entirely, but disabling that works perfect

I have this option
```lua
vim.o.clipboard = 'unnamedplus'
```

**Comment by Shourai** [comment]
With the following config:

```
  use {
  "aserowy/tmux.nvim",
  config = function()
    require("tmux").setup({
      copy_sync = { enable = true,
      redirect_to_clipboard = true },
      navigation = { enable_default_keybindings = true },
      logging = { file = "debug" },
      resize = { enable_default_keybindings = true } })
    end
  }

```
Not sure if I set the configuration for logging correctly, but I don't get anything _new_ written to my neovim log file.

After yanking in tmux

tmux list-buffers:
```
❯ tmux list-buffers
buffer0: 15 bytes: "tmux nvim test\n"
```

nvim registers
```
:reg
Type Name Content
  l  ""   ❯ tmux list-buffers^Jbuffer0: 15 bytes: "tmux nvim test\n"^J
  l  "0   ❯ tmux list-buffers^Jbuffer0: 15 bytes: "tmux nvim test\n"^J
  c  "1   buffer0: 15 bytes: "tmux nvim test\n"
  l  "2   tmux nvim test^J
  c  "3   [redacted]
  c  "4   [redacted]
  c  "5   ow
  c  "6   :57 ago)^JLast configured: 2021-08-05 10:51:40 UTC (-2:00:-29
  l  "7   Can't adjust the time of day: Operation not permitted^J
  c  "8   [redacted]
  l  "9   Can't adjust the time of day: Operation not permitted^J
  c  "a   ignorecase
  c  "g   xk
  c  "k   kkkkkkkkkkkkkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
  c  "o   ^[
  c  "q   ^G^M^M
  c  "u   uuuuuu^R^Rukkkkkkkkkkkkkkkkkkkkkkk
  c  "-
  l  "*   ❯ tmux list-buffers^Jbuffer0: 15 bytes: "tmux nvim test\n"^J
  l  "+   ❯ tmux list-buffers^Jbuffer0: 15 bytes: "tmux nvim test\n"^J
  c  "/   107
```
----

After yanking from nvim:

```
❯ tmux list-buffers
buffer9: 1028 bytes: ":reg\nType Name Content\n  l  ""   this text is yanked from nvim^J\n  l  "0   this text is yanked from nvim^J\n  l  "1   this text is yanked from nvim^J\n  l  "2   ^J\n  l  "3   ^J\n  l  "4   ❯ tmux..."
buffer8: 30 bytes: "this text is yanked from nvim\n"
buffer7: 30 bytes: "this text is yanked from nvim\n"
buffer6: 1 bytes: "\n"
buffer5: 1 bytes: "\n"
buffer4: 60 bytes: "❯ tmux list-buffers\nbuffer0: 15 bytes: "tmux nvim test\\n"\n"
buffer3: 1006 bytes: ":reg\nType Name Content\n  l  ""   ❯ tmux list-buffers^Jbuffer0: 15 bytes: "tmux nvim test\\n"^J\n  l  "0   ❯ tmux list-buffers^Jbuffer0: 15 bytes: "tmux nvim test\\n"^J\n  c  "1   buffer0: 15 byt..."
buffer2: 60 bytes: "❯ tmux list-buffers\nbuffer0: 15 bytes: "tmux nvim test\\n"\n"
buffer1: 37 bytes: "buffer0: 15 bytes: "tmux nvim test\\n""
buffer0: 15 bytes: "tmux nvim test\n"

```

```
:reg
Type Name Content
  l  ""   this text is yanked from nvim^J
  l  "0   this text is yanked from nvim^J
  l  "1   this text is yanked from nvim^J
  l  "2   ^J
  l  "3   ^J
  l  "4   ❯ tmux list-buffers^Jbuffer0: 15 bytes: "tmux nvim test\n"^J
  l  "5   :reg^JType Name Content^J  l  ""   ❯ tmux list-buffers^Jbuffer0: 15 bytes: "tmux nvim test\n"^J^J  l  "0   ❯ tmux list-buffers^Jbuffer0: 15 bytes:
  l  "6   ❯ tmux list-buffers^Jbuffer0: 15 bytes: "tmux nvim test\n"^J
  c  "7   buffer0: 15 bytes: "tmux nvim test\n"
  l  "8   tmux nvim test^J
  l  "9   [redacted]
  c  "a   ignorecase
  c  "g   xk
  c  "i   Ya<80>kb<80>kb[^[
  c  "k   kkkkkkkkkkkkkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
  c  "o   ^[
  c  "q   ^G^M^M
  c  "u   uuuuuu^R^Rukkkkkkkkkkkkkkkkkkkkkkk
  c  "-
  l  "*   this text is yanked from nvim^J
  l  "+   this text is yanked from nvim^J
  c  ".   <80>kb<80>kbthis y<80>kbtext is a<80>kbyanked from ne<80>kbvim
  c  ":   reg
  c  "/   107
```

**Comment by aserowy** [comment]
heho,

to get logging:

require("tmux").setup({
      copy_sync = { enable = true,
          redirect_to_clipboard = true },
      navigation = { enable_default_keybindings = true },
      resize = { enable_default_keybindings = true } 
      },
     { file = "debug" })
end

strange that :reg and buffer information are synced as well. i mean it syncs but broken af^^ buffer 9 for example in the last tmux list-buffers.

i cannot even reproduce it.

**Comment by Shourai** [comment]
Could it be that it has something to do with the way I yank from tmux?
These are my keybindings:

```
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi r send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard' \; display-message "copied to system clipboard"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind-key p run "xclip -o | tmux load-buffer - ; tmux paste-buffer"
bind -n C-S-v run "xclip -o | tmux load-buffer - ; tmux paste-buffer"
```

I'll try setting the logging level to debug later and report back.

**Comment by aserowy** [comment]
i guess you should try to let tmux handle the clipboard entirely. Works cool for me, without using xclip directly.

https://github.com/tmux-plugins/tmux-yank#linux states, working with a new tmux and having xclip installed, it should yank to clipboard out of the box. (it works on my end on wsl2 and mac).

**Comment by Shourai** [comment]
I can't seem to get it to work without piping it to xclip.
Using only `bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel` it's not working.

Doing the above again I get:

## Yanking from tmux
```
❯ tmux list-buffers                                                              
buffer1: 18 bytes: "yanking from tmux\n"                                                                                   
buffer0: 18 bytes: "yanking from tmux\n"
```

```
:reg
Type Name Content
  l  ""   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\n"^Jbuffer0: 18 bytes: "yanking from tmux\n"^J
  l  "0   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\n"^Jbuffer0: 18 bytes: "yanking from tmux\n"^J
  l  "1   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\n"^Jbuffer0: 18 bytes: "yanking from tmux\n"^J
  l  "2   yanking from tmux^J
  l  "3   yanking from tmux^J
  c  "4   config/tmux ma
  c  "5   et-clipboard
  c  "6   onfig/tmux mas
  c  "7   onfig/t^Jm tmux.
  l  "8   nfig/tmux master*^J^Jconf^J
  c  "9   .confi
  c  "a   ignorecase
  c  "g   xk
  c  "i   Ya<80>kb<80>kb[^[
  c  "k   kkkkkkkkkkkkkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
  c  "o   ^[
  c  "q   ^G^M^M
  c  "u   uuuuuu^R^Rukkkkkkkkkkkkkkkkkkkkkkk
  c  "-   }
  l  "*   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\n"^Jbuffer0: 18 bytes: "yanking from tmux\n"^J
  l  "+   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\n"^Jbuffer0: 18 bytes: "yanking from tmux\n"^J
  c  "/   set-clipboard
```

## Yanking from vim
```
❯ tmux list-buffers
buffer7: 29 bytes: "this text is yanked from vim\n"
buffer6: 29 bytes: "this text is yanked from vim\n"
buffer5: 1019 bytes: ":reg\nType Name Content\n  l  ""   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\\n"^Jbuffer0: 18 bytes: "yanking from tmux\\n"^J\n  l  "0   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "y..."
buffer4: 1076 bytes: ":reg\nType Name Content\n  l  ""   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\\n"^Jbuffer0: 18 bytes: "yanking from tmux\\n"^J\n  l  "0   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "y..."
buffer3: 104 bytes: "❯ tmux list-buffers\nbuffer1: 18 bytes: "yanking from tmux\\n"\nbuffer0: 18 bytes: "yanking from tmux\\n"\n"
buffer2: 104 bytes: "❯ tmux list-buffers\nbuffer1: 18 bytes: "yanking from tmux\\n"\nbuffer0: 18 bytes: "yanking from tmux\\n"\n"
buffer1: 18 bytes: "yanking from tmux\n"
buffer0: 18 bytes: "yanking from tmux\n"
```

```
:reg
Type Name Content
  l  ""   this text is yanked from vim^J
  l  "0   this text is yanked from vim^J
  l  "1   this text is yanked from vim^J
  c  "2   :reg^JType Name Content^J  l  ""   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\n"^Jbuffer0: 18 bytes: "yanking from tmux\n"^J^J  l  "0   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\n"^Jbuffer0: 18 bytes: "yanking from tmux\n"^J^J  l  "1   ❯ tmux list-buffers^Jbuffer1: 18 byt
  l  "3   :reg^JType Name Content^J  l  ""   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\n"^Jbuffer0: 18 bytes: "yanking from tmux\n"^J^J  l  "0   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\n"^Jbuffer0: 18 bytes: "yanking from tmux\n"^J^J  l  "1   ❯ tmux list-buffers^Jbuffer1: 18 byt
  l  "4   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\n"^Jbuffer0: 18 bytes: "yanking from tmux\n"^J
  l  "5   ❯ tmux list-buffers^Jbuffer1: 18 bytes: "yanking from tmux\n"^Jbuffer0: 18 bytes: "yanking from tmux\n"^J
  l  "6   yanking from tmux^J
  l  "7   yanking from tmux^J
  l  "8   nfig/tmux master*^J^Jconf^J
  c  "9   .confi
  c  "a   ignorecase
  c  "g   xk
  c  "i   Titii^[
  c  "k   kkkkkkkkkkkkkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
  c  "o   ^[
  c  "q   ^G^M^M
  c  "u   uuuuuu^R^Rukkkkkkkkkkkkkkkkkkkkkkk
  c  "-   }
  l  "*   this text is yanked from vim^J
  l  "+   this text is yanked from vim^J
  c  ".   this text is fr<80>kb<80>kbyanked from i<80>kbvim
  c  ":   reg
  c  "/   set-clipboard
```

## Logs
```
❯ cat tmux.nvim.log
Wed 11 Aug 2021 01:41:37 PM CEST debug
setup copy
Wed 11 Aug 2021 01:41:37 PM CEST debug
setup navigate
Wed 11 Aug 2021 01:41:37 PM CEST debug
setup resize
Wed 11 Aug 2021 01:41:37 PM CEST debug
sync_registers: nil
Wed 11 Aug 2021 01:43:19 PM CEST debug
regcontents = {
  "this text is yanked from vim"
}
visual = "false"
regname = ""
operator = "y"
regtype = "V"
inclusive = "true"

Wed 11 Aug 2021 01:43:19 PM CEST debug
this text is yanked from vim

Wed 11 Aug 2021 01:43:21 PM CEST debug
sync_registers: nil
Wed 11 Aug 2021 01:43:52 PM CEST debug
sync_registers: nil
Wed 11 Aug 2021 01:43:52 PM CEST debug
sync_registers: nil
Wed 11 Aug 2021 01:43:54 PM CEST debug
sync_registers: nil
Wed 11 Aug 2021 01:43:54 PM CEST debug
sync_registers: nil
Wed 11 Aug 2021 01:43:55 PM CEST debug
sync_registers: nil
Wed 11 Aug 2021 01:43:56 PM CEST debug
sync_registers: nil

```

**Comment by aserowy** [comment]
i must admit, i have zero clue, why it is not working -_-

Or is it working and you copied 

❯ tmux list-buffers                                                              
buffer1: 18 bytes: "yanking from tmux\n"                                                                                   
buffer0: 18 bytes: "yanking from tmux\n"

before calling :reg in nvim? That way the copy would also get synced. Besides the sync without getting tmux for system clipboard to work the whole structure will not work for system clipboard harmonization.

Thus, i think it would be wise to make the clipboard option configurable. That way, you could use xclip in tmux and unnamed plus in nvim. With this you would get sync for regs 0 till 9 without sacrificing the current working way for your clipboard.

Would that help?

**Comment by Shourai** [comment]
It seems I am the only one with this issue at the moment.
For now my setup works fine with xclip so I would suggest leaving things as is and I will disable the `copy_sync` functionality for now.
If there are more people facing this issue later on, maybe we can look into it again.

Also I am not sure if the issue that @pedro757 is having is related to this.

Thanks for your time!

**Comment by pedro757** [comment]
> It seems I am the only one with this issue at the moment.
> For now my setup works fine with xclip so I would suggest leaving things as is and I will disable the `copy_sync` functionality for now.
> If there are more people facing this issue later on, maybe we can look into it again.
> 
> Also I am not sure if the issue that @pedro757 is having is related to this.
> 
> Thanks for your time!

I think it's related with your problem, because I disabled `copy_sync` and it works perfect for me, maybe that option should be disabled by default.

**Comment by aserowy** [comment]
Heho,

just hopping in to confirm that all features are disabled by default.


Kind regards

**Comment by pedro757** [comment]
ok didn't notice :zany_face:

**Comment by aserowy** [comment]
Heho,

i added an option to disable the set of vim.g.clipboard. Thus, you can try to disable it and use your normal workflow. This should (i cannot test it on my end) handle syncs within nvim like you configured it and get the shared history within tmux and nvim. If  you have spare time, it would be cool to test it. The option is called `sync_clipboard` (readme is updated as well).

Kind regards

**Comment by Shourai** [comment]
Hey @aserowy,

thanks for the effort!
I have tested it with the following config:

```
  use {
    "aserowy/tmux.nvim",
    config = function()
      require("tmux").setup({
        copy_sync = {
          enable = true,
          redirect_to_clipboard = true,
          register_offset = 0,
          sync_clipboard = true,
          sync_deletes = true,
        },
        navigation = { enable_default_keybindings = true },
        resize = { enable_default_keybindings = true } })
      end
    }
```

Works on my end without having to change anything else in my config.
It sort of confuses me, looking at the code it seems that I should set `sync_clipboard = false,` for it to work instead of `true`.

**Comment by aserowy** [comment]
cool that it works :D even without the disable! 👍 

Maybe pedro can give us an insight :)

**Comment by Shourai** [comment]
I might have spoken too soon.
Previously I only closed neovim and tmux but left my terminal emulator running.
It seems it doesn't reload the settings correctly for some reason if I open tmux again.

After completely shutting down my terminal emulator and then starting tmux and neovim.
It seems I do need to set `sync_clipboard = false`

**Comment by aserowy** [comment]
nonetheless, now you can set it and can use the feature partially 💯 

honor us again soon :D and ty for your help

PS: can you please close the issue, if it works for you this way?

**Comment by Shourai** [comment]
Thanks!
Commit: https://github.com/aserowy/tmux.nvim/commit/6ad3f6b67159e24e88d60ebcf333b76fea7dab1f fixes the issue.
Closing issue.
