### ISSUE TITLE
add option to change resize step

### ISSUE THREAD

**Issue by hnspn** [aserowy/tmux.nvim#2]
Cool plugin,
Maybe add a way to increase the resize step
It could be confired like this
```lua 
{
    navigation = {
      ...
    },
    resize = {
        enable_default_keybindings = true,
        resize_step = 3,m
    }
}
```

**Comment by aserowy** [comment]
Heho,

i divided the configuration into x and y axis to enable full customization. Hope this fill your needs.

Kind regards
