### ISSUE TITLE
Misconception of #{pane_at_top}

### ISSUE THREAD

**Issue by pedro757** [aserowy/tmux.nvim#20]
Recently I migrate from vim-tmux-navigator but I encounter this bug, when the vim pane is zoomed in, it does not cycle, no matter what `persist_zoom` you've set

After some debugging I found that `#{pane_at_top}` means if the pane is at the top at the specific moment you ask.

That's why when we run this in a zoomed in pane  we get `1` and when we run that in a zoomed out pane we get `0`
`tmux -S <YOUR-SESSION-SOCKET> display-message -p '#{pane_at_top}'`

That variable is not appropiate to find out if it has a neighbor in `X` direction, nor to find if it's the very last pane, so basically it's useless for that purpose

So my recommendation is to go back to the behavior of the plugin `vim-tmux-navigator`, What do you think?

**Comment by aserowy** [comment]
Heho,

ty for the heads up. Yes it is useless in this circumstance :D. We should rework the has_neighbor(d) function in wrapper.lua. You can file a pr if you like :). If not, I'll take care of it in the coming week.
Maybe the vim tmux navigator way is the only one to support this behaviour. I'll take a deeper look.

Kind regards
Alexander

**Comment by aserowy** [comment]
Ok, i looked into tmux navigator. It seems, that the plugin does simply not check navigation beyond vim border while handling not persistent zoom. Thus, no rework needed. *puh* :]
We only need to prevent the check while zoomed. I'll increase test coverage while reworking the logic. It will take a little bit more effort. But next week, i can go nuts 💯 

Kind regards

**Comment by pedro757** [comment]
With this pr we keep `persist_zoom`, The only feature that is broken is cycle_free, because that variable is not appropiate to find is there are neighbors when is zoomed in.

The `has_neighbor` function is still usefull in the resize functions, because it would be weird is someone resize pane when the pane is zoomed in. But I don't really know I don't use this feature

**Comment by aserowy** [comment]
Heho,

why remove the whole functionality? Besides in zoom, it works (and im using it). A quick workaround would be to check if tmux zoom is active and prevent the has_neighbor function if so.

Kind regards

**Comment by pedro757** [comment]
I think we could do better, Searching in the `man tmux` pages I found these variables:

- `#{window_panes}` == Amount of panes in that window
- `#{pane_index}` == Position From left to right then down
- `#{pane_id}` == Unique pane id
- `#{window_layout}` == Layout of the panes in that window

The problem with this last one is the rare format in which is outputted
**e.g.**
![image](https://user-images.githubusercontent.com/30637426/128750850-1c4917f8-9b13-46b9-92f3-59a3643e0c1e.png)

`tmux -S <YOUR_SOCKET> display -p '#{window_layout}'`

**Output:**

`405f,205x50,0,0[205x25,0,0{102x25,0,0,1,51x25,103,0,5,50x25,155,0,6},205x24,0,26{102x24,0,26,2,102x24,103,26,7}]`

I think it's somthing like this: `idk,SIZE,idk,idk,ID`

Maybe we could infer if there are neighbors with that variables,

### I'm going to try this:
1. If the pane is zoomed in, check how many panes are in that window with `#{window_pane}`
2. Then check what is the pane index with `#{pane_index}`
3. If the option `cycle_free` is enabled when the pane index is the first, prevent from doing `select-pane -U` or `select-pane -L`
4. If the option `cycle_free` is enabled when the pane index is the last, prevent from doing `select-pane -D` or `select-pane -R`

If this does not work, we should try to understand the `#{window_layout}` variable
