### ISSUE TITLE
Stopped working across nvim to nvim in tmux pane split

### ISSUE THREAD

**Issue by oblitum** [aserowy/tmux.nvim#25]
If I split tmux window in two panes side by side and run nvim on each split, the mappings won't move from one split to another, it only works in:

- nvim window to nvim window
- nvim window to tmux pane
- tmux pane to nvim window
- tmux pane to tmux pane

It not working in:

- nvim window in tmux pane to nvim window in another tmux pane

I'm not sure whether it used to work, I suspect it did because I've been using it for quite a while and only noticed this problem lately.

**Comment by aserowy** [comment]
Heho,

ty for the heads up. Ill look into it asap.

Kind regards

**Comment by charlesbjohnson** [comment]
I believe that I am also experiencing this issue:

```
+-----+-----+
|     |     |
|  1  |  2  |
|_____|_____|
```

I can move from pane 1 to pane 2, but not pane 2 to pane 1. It appears that this line is preventing the navigation:

https://github.com/aserowy/tmux.nvim/blob/6ad3f6b67159e24e88d60ebcf333b76fea7dab1f/lua/tmux/wrapper.lua#L98-L100

**Comment by aserowy** [comment]
heho,

i reverted the pr for #24 and implemented a hack. Can you please test, if everything is working as expected now? (Because i cannot reproduce the behaviour on my end)

Ty and kind regards
Alexander

**Comment by oblitum** [comment]
@aserowy thx, this fixed it for me.

**Comment by geofflangenderfer** [comment]
I'm unable to navigate left. Up, down, and right work.

Navigating right at the right border does jump me to the left vim pane, though.
