### ISSUE TITLE
Adding "-n " at the start of the pasted line

### ISSUE THREAD

**Issue by juliangsibecas** [aserowy/tmux.nvim#38]
Hi!

After I do `V y p` or `dd p` the plugin inserts "-n " at the start of the pasted line when copy_sync is enabled.

![image](https://user-images.githubusercontent.com/25715495/134093361-2cae5c57-6cb3-4f09-a71f-42fb3a7d8dd6.png)

**Comment by aserowy** [comment]
Hi,

ty for the heads up. I will look into it asap. Probably in the next 2-3 days. Have to finish an article first. Thus, please bear with me :D

Kind regards
Alexander

**Comment by juliangsibecas** [comment]
I was using neovim 0.6.0. After installing 0.5.0 it is working properly!

**Comment by juliangsibecas** [comment]
No problem Alex! Take your time :}

**Comment by aserowy** [comment]
Should work now. Plz give me a heads up, if you get any trouble.

Kind regards
