### ISSUE TITLE
Copy sync * and + registers only

### ISSUE THREAD

**Issue by adwinying** [aserowy/tmux.nvim#43]
How can I choose to sync only the * and + registers with tmux?

**Comment by aserowy** [comment]
Heho,

I guess you could use

-- offset controls where register sync starts
-- e.g. offset 2 lets registers 0 and 1 untouched
register_offset = 10,

This would leave only the unnamed register and clipboard synced.
If you need an option to leave the unnamed just reply and I'll do my very best 😁


Kind regards

Alexander

**Comment by aserowy** [comment]
Heho,

added the option to disable the register. Can you give me a short hint if it suits your needs?

Kind regards

**Comment by adwinying** [comment]
Hmm... I still can't get it to work the way I want :/

I tried the following commands:

```
yy
dd
"+yy
"+dd
"*yy
"*dd
```

And I don't want `yy` and `dd` to sync with tmux's buffers but `yy` is still synced to tmux's buffers...

Are my configs set correctly?

```lua
tmux.setup {
  copy_sync = {
    -- enables copy sync and overwrites all register actions to
    -- sync registers *, +, unnamed, and 0 till 9 from tmux in advance
    enable = true,

    -- TMUX >= 3.2: yanks (and deletes) will get redirected to system
    -- clipboard by tmux
    redirect_to_clipboard = false,

    -- offset controls where register sync starts
    -- e.g. offset 2 lets registers 0 and 1 untouched
    register_offset = 10,

    -- sync clipboard overwrites vim.g.clipboard to handle * and +
    -- registers. If you sync your system clipboard without tmux, disable
    -- this option!
    sync_clipboard = true,

    -- syncs deletes with tmux clipboard as well, it is adviced to
    -- do so. Nvim does not allow syncing registers 0 and 1 without
    -- overwriting the unnamed register. Thus, ddp would not be possible.
    sync_deletes = false,

    -- syncs the unnamed register with the first buffer entry from tmux.
    sync_unnamed = false,
  },
  ...
```

**Comment by aserowy** [comment]
Hi,

now i get what you are trying to achieve! I guess this would be out of scope for the plugin configuration wise. Just disable the copy feature and configure the clipboard yourself.

You can look into copy.lua -> setup() on how to register a clipboard. In wrapper/tmux.lua you will find how to check if a tmux session is started.

Hope it helps. Any questions, just ask here :dagger: 

Kind regards
Alexander
