### ISSUE TITLE
Disable Keybindings in insert mode

### ISSUE THREAD

**Issue by ovidius72** [aserowy/tmux.nvim#55]
Hi, thanks for this great plugin. As the title state I'm looking for a way to enable navigation from nvim to tmux only when i'm in normal mode and not insert mode. Currently when I type <C-h> to delete the previous char it switches to the next tmux panel from nvim.
Is there any option to do that ?
Thanks in advance.

**Comment by aserowy** [comment]
Heho,

you can bind the movement on your own. Look at the readme.

Look at the last paragraph of https://github.com/aserowy/tmux.nvim#navigation

Kind regards

**Comment by ovidius72** [comment]
Hi. Yes I've already tried with those keybindings but I couldn't find a way to apply them only in normal mode. I think there should be a way to tell tmux which mode is currently on in vim.
