### ISSUE TITLE
resize_step_x and resize_step_y is not used in tmux command

### ISSUE THREAD

**Issue by ErickChacon** [aserowy/tmux.nvim#63]
The arguments `size_step_x` and `size_step_y` is not used to define the tmux command.  The following function defines the step equals to `1`. Can we please update this function to use both arguments?

https://github.com/aserowy/tmux.nvim/blob/6ed82c5f6ac89eedf21982c07abbcf530b2485bd/lua/tmux/wrapper/tmux.lua#L92-L94

**Comment by aserowy** [comment]
Hi,

if you like, file a pr. I am completly locked in rl currently :smile: 

Kind regards

**Comment by BlakeJC94** [comment]
I stumbled across the same issue, figured it was a relatively simple change to make. Submitted a PR to address this
