### ISSUE TITLE
Resizing fails in a specific scenario

### ISSUE THREAD

**Issue by mojasp** [aserowy/tmux.nvim#78]
Resizing works fine except for one specific scenario:
When there is tmux pane on the left, and a vim pane on the right that has a horizontal split, resizing from the vim pane(from either split) will not work:
![grafik](https://user-images.githubusercontent.com/9821375/187626602-d6fd7a6b-8b1f-4fbb-a9aa-89e568fcf23b.png)

When there is no horizontal split it will work; resizing from the tmux pane will work, if the vim instance is on the left instead it will work, etc...

Only this specific scenario just does nothing

**Comment by maxcountryman** [comment]
I'm having general trouble with resizing, altho it may also be this case: currently resizing is not working for me.

**Comment by aserowy** [comment]
hmm, i need to analyse the behavior (probably at the coming weekend). If it cant wait that long, plz consider filing a pr.

Regards
Alexander

**Comment by mojasp** [comment]
I submitted a PR, thank you for the great plugin by the way :)
