### ISSUE TITLE
[FR] Omit setup step if use default settings

### ISSUE THREAD

**Issue by babygau** [aserowy/tmux.nvim#80]
Some plugins allow us to omit setup call if we use default setting. Please only force user to setup call if they wanna change default behavior. This will help remove boilerplate code in our config. Thank you

**Comment by aserowy** [comment]
heho,

ty for the idea. need some time to get this done. if you want it now, please file a pr :)

regards
Alexander

**Comment by aserowy** [comment]
Merged it finally 🙃
