### ISSUE TITLE
Request to use a fork of vim-tmux-navigator tpm with resize support

### ISSUE THREAD

**Issue by joeveiga** [aserowy/tmux.nvim#93]
Hello!

Have you considered forking vim-tmux-navigator (the tmux config, not the vim plugin) so that we could push the resize config into that repo? Main motivation is I'd rather have the tmux conf snippet for resizing moved into the tpm plugin, rather than copy pasting it into my own (and everyone else's) tmux.conf.

I could create the tpm plugin for myself, but I think it'd be beneficial for everyone to be able to do just:
```tmux
set -g @plugin 'aserowy/tmux.nvim'
```

I can submit a PR if you'r open to it.
Thanks!

**Comment by aserowy** [comment]
Heho, PR are always welcome!
